#!/usr/bin/env python3
"""GitHub Issue notification module.

Creates GitHub Issues with formatted lists of new relevant papers.
Uses the GitHub REST API via environment variables for authentication.
"""

from __future__ import annotations

import json
import logging
import os
import urllib.request
import urllib.error
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any

logger = logging.getLogger(__name__)


@dataclass
class PaperInfo:
    doi: str
    title: str
    authors: list[str]
    journal: str | None
    year: str | None
    score: int
    priority: str
    matched_tiers: list[str]
    matched_keywords: list[str]
    url: str


def format_paper_markdown(paper: PaperInfo, index: int) -> str:
    authors_str = ", ".join(paper.authors[:3])
    if len(paper.authors) > 3:
        authors_str += " et al."

    tier_badges = " ".join(
        [
            f"`{t.replace('tier', 'T').replace('_', ' ').title()}`"
            for t in paper.matched_tiers[:3]
        ]
    )
    keywords_str = ", ".join(paper.matched_keywords[:5])

    lines = [
        f"### {index}. {paper.title}",
        "",
        f"**Authors:** {authors_str}",
        f"**Journal:** {paper.journal or 'N/A'} ({paper.year or 'N/A'})",
        f"**DOI:** [{paper.doi}]({paper.url})",
        f"**Relevance Score:** {paper.score} ({paper.priority})",
        f"**Matched Tiers:** {tier_badges}",
        f"**Keywords:** {keywords_str}",
        "",
    ]

    return "\n".join(lines)


def format_issue_body(
    papers: list[PaperInfo],
    from_date: str,
    to_date: str,
    total_fetched: int,
    journals_count: int,
) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    high_priority = [p for p in papers if p.priority == "HIGH"]
    medium_priority = [p for p in papers if p.priority == "MEDIUM"]
    low_priority = [p for p in papers if p.priority == "LOW"]

    lines = [
        f"# Weekly Literature Monitor Report",
        "",
        f"**Period:** {from_date} to {to_date}",
        f"**Generated:** {now}",
        "",
        "## Summary",
        "",
        f"- **Total papers fetched:** {total_fetched}",
        f"- **Relevant papers found:** {len(papers)}",
        f"- **Journals monitored:** {journals_count}",
        "",
        "| Priority | Count |",
        "|----------|-------|",
        f"| HIGH | {len(high_priority)} |",
        f"| MEDIUM | {len(medium_priority)} |",
        f"| LOW | {len(low_priority)} |",
        "",
    ]

    if high_priority:
        lines.append("---")
        lines.append("")
        lines.append("## HIGH Priority Papers")
        lines.append("")
        for i, paper in enumerate(high_priority, 1):
            lines.append(format_paper_markdown(paper, i))

    if medium_priority:
        lines.append("---")
        lines.append("")
        lines.append("## MEDIUM Priority Papers")
        lines.append("")
        for i, paper in enumerate(medium_priority, 1):
            lines.append(format_paper_markdown(paper, i))

    if low_priority and len(low_priority) <= 20:
        lines.append("---")
        lines.append("")
        lines.append("## LOW Priority Papers")
        lines.append("")
        for i, paper in enumerate(low_priority, 1):
            lines.append(format_paper_markdown(paper, i))
    elif low_priority:
        lines.append("---")
        lines.append("")
        lines.append(
            f"## LOW Priority Papers ({len(low_priority)} total, showing top 20)"
        )
        lines.append("")
        for i, paper in enumerate(low_priority[:20], 1):
            lines.append(format_paper_markdown(paper, i))

    lines.append("---")
    lines.append("")
    lines.append(
        "*Generated by [Weekly Literature Monitor](https://github.com/yourusername/weekly-literature-monitor)*"
    )

    return "\n".join(lines)


def create_github_issue(
    title: str,
    body: str,
    labels: list[str] | None = None,
    repo: str | None = None,
    token: str | None = None,
) -> dict[str, Any] | None:
    if token is None:
        token = os.environ.get("GITHUB_TOKEN")
    if repo is None:
        repo = os.environ.get("GITHUB_REPOSITORY")

    if not token or not repo:
        logger.error(
            "GITHUB_TOKEN and GITHUB_REPOSITORY environment variables required"
        )
        return None

    url = f"https://api.github.com/repos/{repo}/issues"

    payload: dict[str, Any] = {
        "title": title,
        "body": body,
    }
    if labels:
        payload["labels"] = labels

    data = json.dumps(payload).encode("utf-8")

    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "Content-Type": "application/json",
        "X-GitHub-Api-Version": "2022-11-28",
    }

    req = urllib.request.Request(url, data=data, headers=headers, method="POST")

    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        logger.error(f"GitHub API error: {e.code} - {e.read().decode()}")
        return None
    except urllib.error.URLError as e:
        logger.error(f"Network error: {e}")
        return None


def notify_new_papers(
    papers: list[PaperInfo],
    from_date: str,
    to_date: str,
    total_fetched: int,
    journals_count: int,
) -> bool:
    if not papers:
        logger.info("No relevant papers to report.")
        return True

    high_count = len([p for p in papers if p.priority == "HIGH"])
    title = f"[Weekly Report] {len(papers)} relevant papers ({from_date} to {to_date})"
    if high_count > 0:
        title = f"[Weekly Report] {len(papers)} papers, {high_count} HIGH priority ({from_date} to {to_date})"

    body = format_issue_body(papers, from_date, to_date, total_fetched, journals_count)

    labels = ["literature-monitor", "automated"]
    if high_count > 0:
        labels.append("high-priority")

    result = create_github_issue(title, body, labels)

    if result:
        logger.info(f"Created GitHub Issue: {result.get('html_url')}")
        return True
    else:
        logger.error("Failed to create GitHub Issue")
        return False
